// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/component"

var (
	Type      = component.MustNewType("clientcert")
	ScopeName = "github.com/danielwegener/otelcol-processor-clientcert"
)

const (
	TracesStability   = component.StabilityLevelDevelopment
	MetricsStability  = component.StabilityLevelDevelopment
	LogsStability     = component.StabilityLevelDevelopment
	ProfilesStability = component.StabilityLevelDevelopment
)
